# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 18:16
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import picklefield.fields
import utastar.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='alternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b' ', max_length=200, verbose_name=b'Name')),
                ('ranking', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='criterion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion_name', models.CharField(max_length=200, verbose_name=b'Name')),
                ('criterion_type', models.IntegerField(choices=[(0, b'Quantitative'), (1, b'Qualitative')], default=0, verbose_name=b'Type')),
                ('criterion_monotonicity', models.IntegerField(choices=[(0, b'Ascending'), (1, b'Descending')], default=0, verbose_name=b'Monotonicity')),
                ('criterion_a', models.IntegerField(choices=[(2, b'Second Grade(a = 2)'), (3, b'Third Grade(a = 3)'), (4, b'Forth Grade(a = 4)'), (5, b'Fifth Grade(a = 5)'), (6, b'Sixth Grade(a = 6)'), (7, b'Seventh Grade(a = 7)'), (8, b'Eighth Grade(a = 8)'), (9, b'Ninth Grade(a = 9)'), (10, b'Tenth Grade(a = 10)')], default=5, help_text=b'Select one of the ten scales available.', verbose_name=b'Scale')),
                ('criterion_worst', models.FloatField(blank=True, default=b' ', help_text=b'Type the worst value the criterion can take.', verbose_name=b'Worst Value')),
                ('criterion_best', models.FloatField(blank=True, default=b' ', help_text=b'Type the best value the criterion can take.', verbose_name=b'Best Value')),
            ],
        ),
        migrations.CreateModel(
            name='criterionvalue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('alt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utastar.alternative')),
                ('crit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utastar.criterion')),
            ],
        ),
        migrations.CreateModel(
            name='global_utilities_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_utilities_post', models.ImageField(upload_to=utastar.models.handle_gup_file)),
            ],
        ),
        migrations.CreateModel(
            name='marginal_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marginal_post', models.ImageField(upload_to=utastar.models.handle_mp_file)),
            ],
        ),
        migrations.CreateModel(
            name='metafile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_file', models.FileField(upload_to=utastar.models.handle_meta_file)),
            ],
        ),
        migrations.CreateModel(
            name='multicriteriafile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multicriteria_file', models.FileField(upload_to=utastar.models.handle_multicriteria_file)),
            ],
        ),
        migrations.CreateModel(
            name='research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'\xce\x95\xcf\x80\xce\xb9\xce\xbb\xce\xad\xce\xbe\xcf\x84\xce\xb5 \xcf\x84\xce\xbf \xcf\x8c\xce\xbd\xce\xbf\xce\xbc\xce\xb1 \xcf\x84\xce\xb7\xcf\x82 \xce\xad\xcf\x81\xce\xb5\xcf\x85\xce\xbd\xce\xb1\xcf\x82.', max_length=200, verbose_name=b'\xce\x8c\xce\xbd\xce\xbf\xce\xbc\xce\xb1 \xce\x88\xcf\x81\xce\xb5\xcf\x85\xce\xbd\xce\xb1\xcf\x82')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2017, 5, 21, 18, 16, 37, 864000, tzinfo=utc))),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='utastar_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', picklefield.fields.PickledObjectField(editable=False)),
                ('research', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utastar.research')),
            ],
        ),
        migrations.CreateModel(
            name='weights_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_weights_post', models.ImageField(upload_to=utastar.models.handle_mwp_file)),
                ('research', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utastar.research')),
            ],
        ),
        migrations.AddField(
            model_name='multicriteriafile',
            name='research',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utastar.research'),
        ),
        migrations.AddField(
            model_name='metafile',
            name='research',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utastar.research'),
        ),
        migrations.AddField(
            model_name='marginal_image',
            name='research',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utastar.research'),
        ),
        migrations.AddField(
            model_name='global_utilities_image',
            name='research',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utastar.research'),
        ),
        migrations.AddField(
            model_name='criterionvalue',
            name='research',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utastar.research'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='criterion_research',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utastar.research'),
        ),
        migrations.AddField(
            model_name='alternative',
            name='alternative_research',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utastar.research'),
        ),
        migrations.AddField(
            model_name='alternative',
            name='criteria',
            field=models.ManyToManyField(blank=True, through='utastar.criterionvalue', to='utastar.criterion'),
        ),
    ]
