# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 18:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('utastar', '0005_auto_20170521_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 21, 18, 19, 58, 16000, tzinfo=utc)),
        ),
    ]
